### ISSUE TITLE
What different between that mod and vanilla ESC button way?

### ISSUE THREAD

**Issue by syorito-hatsuki** [agent-LuluDodo/RebindMyKeys#1]
If click the ESC button in vanilla it will be unbound
![image](https://github.com/agent-LuluDodo/UnbindMyKeys/assets/33298273/e4704685-d8a3-4f35-9c8e-2a801e78c872)
![image](https://github.com/agent-LuluDodo/UnbindMyKeys/assets/33298273/6bced5b2-e180-4643-9b58-16ea773160d4)

**Comment by agent-LuluDodo** [comment]
That is possible?! I should have really done some research first. Currently, there is no difference, but I will allow the esc key to be rebound in the next update.

**Comment by agent-LuluDodo** [comment]
I updated the mod: https://modrinth.com/mod/rebindmykeys/version/2.0
I'm allowing the escape button to be bound to keys, so the unbind button has a purpose.
Many thanks for this issue!
